import type { Metadata } from 'next';
import '../globals.css';
import { inter } from '@/app/fonts';
import AdminLayout from '@/app/(admin)/AdminLayout';

export const metadata: Metadata = {
    title: 'Chubby Dashboard',
    description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="es" className={`${inter.className} antialiased`}>
            <body>
                <AdminLayout>{children}</AdminLayout>
            </body>
        </html>
    );
}
