import type { Metadata } from 'next';
import '../globals.css';
import { inter } from '@/app/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" className={`${inter.className} antialiased`}>
            <body>{children}</body>
        </html>
    );
}
